# Generated by Django 4.0.1 on 2024-02-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_auto_20170818_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='explicit_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url_parts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
